name: notebook
channels:
  - conda-forge
  - rapidsai-nightly
dependencies:
# JUPYTER
  - jupyterlab
  - jupyterhub
  - jupyter-server-proxy
  - nbgitpuller
# CUDA
  - cupy
  - cudatoolkit
  - cudf
  - rmm
  - cuspatial
# DASK
  - dask
  - distributed
  - dask-kubernetes
  - dask-labextension
  - python-graphviz
# OTHER
  - tornado
  - bokeh
  - pip
